[general]
size_t thread_count = 8

[ground]
kitti_base_to_baseX = 1.95
kitti_base_to_baseY = 0
kitti_base_to_baseZ = -1.73

min_outlier_detection_ground_confidence = 1.25
outlier_tolerance = 0.1
patch_size_change_distance = 0.0
minimum_distance_factor = 0.00001
miminum_point_height_threshold = 0.3
minimum_point_height_obstacle_threshold = 0.1
ground_patch_detection_minimum_point_count_threshold = 0.25
distance_factor = 0.0
point_count_cell_variance_threshold = 10
occupied_cells_point_count_factor = 20.0
occupied_cells_decrease_factor = 5.0